[build]
  base = "portfolio-angular"
  command = "npm run build"
  publish = "dist/portfolio-angular/browser"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true
